// solid-package/src/tooltips.tsx
import { template as _template, insert } from "solid-js/web"
import { PrismEditor } from "."
import { JSX, Show, createSignal } from "solid-js"

const template = /* @__PURE__ */ _template(
	"<div class=pce-tooltip style=z-index:5;top:auto;display:flex;overflow-x:clip><div>",
)

/** Function removing the tooltip from the DOM. */
export type HideTooltip = () => void

export type Tooltip = {
	/**
	 * Moves to tooltip to align with the cursor and shows it.
	 * @param preferPlacingAboveCursor Whether the preferred position is above the cursor or not.
	 */
	show(preferPlacingAboveCursor?: boolean): void
	/** Hides the tooltip */
	hide(): void
	/** The element wrapping your tooltip */
	element: JSX.Element
}

/**
 * Utility making it easy to add tooltips positioned on the editor's cursor. Before you
 * can show the tooltip, a {@link cursorPosition} extension must be added to the editor.
 *
 * This works by appending your tooltip to a flex container. You can style this container
 * with the selector `.pce-tooltip` if needed. It has `overflow-x: clip` to prevent your
 * tooltip from overflowing in browsers that support it.
 *
 * This utility is intended to be wrapped in a custom extension that controls when the
 * tooltip is shown. Your extension should then return the container returned by this
 * utility.
 *
 * If you want your tooltip to always be visible when scrolling horizontally, you can add
 * `position: sticky` along with the `right` and `left` CSS properties to it.
 *
 * @param editor Editor you want to add the tooltip to.
 * @param element Element for the tooltip. Should be a single HTML element.
 * @param fixedWidth If false, the tooltip will shrink instead of getting offset to
 * the left if there's not enough space to the right of the cursor. Defaults to `true`.
 * *Note:* Your tooltip element must have `flex-shrink: 0` if `fixedWidth` isn't set to
 * `false`.
 */
export const addTooltip = (
	editor: PrismEditor,
	element: JSX.Element,
	fixedWidth = true,
): Tooltip => {
	const container = template() as HTMLDivElement
	const style = container.style
	const spacer = container.firstChild as HTMLDivElement
	const [open, setOpen] = createSignal(false)

	insert(container, element, null)
	if (!fixedWidth) spacer.style.flexShrink = 0 as any

	return {
		show(above?: boolean) {
			let cursor = editor.extensions.cursor
			if (cursor) {
				let { left, right, top, bottom, height } = cursor.getPosition()
				setOpen(true)
				spacer.style.width = (editor.props.rtl ? right : left) + "px"

				let placeAbove =
					!above == top > bottom && (above ? top : bottom) < container.clientHeight ? !above : above

				style[placeAbove ? "bottom" : "top"] = height + (placeAbove ? bottom : top) + "px"
				style[placeAbove ? "top" : "bottom"] = "auto"
			}
		},
		hide() {
			setOpen(false)
		},
		element: <Show when={open()}>{container}</Show>,
	}
}

// react-package/src/tooltips.ts
import { ReactNode, useCallback, useLayoutEffect, useMemo } from "react"
import { PrismEditor } from "./types"
import { createTemplate } from "./utils/local"
import { createPortal } from "react-dom"
import { useCursorPosition } from "./extensions/cursor"
import { addOverlay } from "./utils"

const template = /* @__PURE__ */ createTemplate(
	"<div class=pce-tooltip style=z-index:5;top:auto;display:flex;overflow-x:clip><div>",
)

/**
 * Moves to tooltip to align with the cursor and shows it.
 * @param preferPlacingAboveCursor Whether the preferred position is above the cursor or not.
 */
export type ShowTooltip = (preferPlacingAboveCursor?: boolean) => void

/** Function removing the tooltip from the DOM. */
export type HideTooltip = () => void

const show = (
	editor: PrismEditor,
	container: HTMLDivElement,
	spacerStyle: CSSStyleDeclaration,
	above?: boolean,
) => {
	let cursor = editor.extensions.cursor
	if (cursor) {
		let { left, right, top, bottom, height } = cursor.getPosition()
		container.parentNode || addOverlay(editor, container)
		spacerStyle.width = (editor.props.rtl ? right : left) + "px"

		let placeAbove =
			!above == top > bottom && (above ? top : bottom) < container.clientHeight ? !above : above

		container.style[placeAbove ? "bottom" : "top"] = height + (placeAbove ? bottom : top) + "px"
		container.style[placeAbove ? "top" : "bottom"] = "auto"
	}
}

/**
 * Same as {@link useTooltip} but accepts a JSX element instead of a DOM node.
 *
 * *Note:* Your tooltip element must have `flex-shrink: 0` if `fixedWidth` isn't set to
 * `false`.
 *
 * @param editor Editor you want to add the tooltip to.
 * @param element JSX element for the tooltip.
 * @param fixedWidth If false, the tooltip will shrink instead of getting offset to
 * the left if there's not enough space to the right of the cursor. Defaults to `true`.
 *
 * @example
 * ```jsx
 * const [show, hide, portal] = useReactTooltip(
 *   editor,
 *   <div style={{ flexShrink: 0 }}>My tooltip</div>,
 * )
 * ```
 * The portal should be returned from an extension.
 */
export const useReactTooltip = (
	editor: PrismEditor,
	element: ReactNode,
	fixedWidth = true,
): [ShowTooltip, HideTooltip, ReactNode] => {
	const container = useMemo(template, [])
	const spacerStyle = (container.firstChild as HTMLDivElement).style

	spacerStyle.flexShrink = fixedWidth ? "" : "0"

	return [
		useCallback(show.bind(editor, editor, container, spacerStyle), []),
		useCallback(() => container.remove(), []),
		createPortal(element, container),
	]
}

/**
 * Utility making it easy to add tooltips positioned on the editor's cursor. Before you
 * can show the tooltip, the {@link useCursorPosition} hook must've been called.
 *
 * This works by appending your tooltip to a flex container. You can style this container
 * with the selector `.pce-tooltip` if needed. It has `overflow-x: clip` to prevent your
 * tooltip from overflowing in browsers that support it.
 *
 * This utility is intended to be wrapped in a custom extension that controls when the
 * tooltip is shown. Your extension should then return the container returned by this
 * utility.
 *
 * If you want your tooltip to always be visible when scrolling horizontally, you can add
 * `position: sticky` along with the `right` and `left` CSS properties to it.
 *
 * @param editor Editor you want to add the tooltip to.
 * @param element HTML Element for the tooltip.
 * @param fixedWidth If false, the tooltip will shrink instead of getting offset to
 * the left if there's not enough space to the right of the cursor. Defaults to `true`.
 *
 * @example
 * const [show, hide] = useTooltip(editor, myElement)
 */
export const useTooltip = (
	editor: PrismEditor,
	element: HTMLElement,
	fixedWidth = true,
): [ShowTooltip, HideTooltip] => {
	const container = useMemo(template, [])
	const spacerStyle = (container.firstChild as HTMLDivElement).style

	useLayoutEffect(() => {
		container.append(element)
		return () => element.remove()
	}, [element])

	spacerStyle.flexShrink = fixedWidth ? "" : "0"
	element.style.flexShrink = fixedWidth ? "0" : ""

	return [
		useCallback(show.bind(editor, editor, container, spacerStyle), []),
		useCallback(() => container.remove(), []),
	]
}
