// react-package/src/code-block/index.tsx
import { ReactNode, useMemo } from "react"
import { highlightTokens, languages, tokenizeText, TokenStream } from "../prism"
import { useStableRef } from "../core"

export type CodeBlockProps = {
	/** Language used for syntax highlighting. */
	language: string
	/** Code in the code block. */
	code: string
	/** Number of spaces a tab is equal to. @default 2 */
	tabSize?: number
	/** Whether or not to display line numbers. @default false */
	lineNumbers?: boolean
	/** Line number of the first line. @default 1 */
	lineNumberStart?: number
	/** Whether or not lines can wrap. @default false */
	wordWrap?: boolean
	/**
	 * Whether or not indentation is preserved on wrapped lines. When `true`, tabs are
	 * replaced with spaces since Chrome doesn't render tabs properly with this enabled.
	 * Defaults to `true` when `wordWrap` is enabled.
	 */
	preserveIndent?: boolean
	/**
	 * Whether or not to display indentation guides. Does support `wordWrap` unlike the
	 * `IndentGuides` editor extension. Does not work with `rtl`. @default false
	 */
	guideIndents?: boolean
	/**
	 * Whether the code block uses right to left directionality. Requires styles from
	 * `prism-react-editor/rtl-layout.css` to work. @default false
	 */
	rtl?: boolean
	/** Inline styles for the container element. */
	style?: Omit<React.CSSProperties, "tabSize" | "counterReset">
	/** Additional classes for the container element. */
	className?: string
	/**
	 * Callback that can be used to modify the tokens before they're stringified to HTML.
	 * Can be used to add rainbow brackets for example.
	 */
	onTokenize?(tokens: TokenStream): void
	children?(codeBlock: PrismCodeBlock, props: CodeBlockProps): ReactNode
}

export type PrismCodeBlock = {
	/** Outermost element of the code block. */
	container?: HTMLPreElement
	/** `<code>` element wrapping the lines and overlays. */
	wrapper?: HTMLElement
	/**
	 * Collection containing the overlays as the first element. The rest of the elements
	 * are the code lines. This means the first line starts at index 1.
	 */
	lines?: HTMLCollectionOf<HTMLDivElement>
}

const CodeBlock = (props: CodeBlockProps) => {
	const {
		onTokenize,
		guideIndents,
		rtl,
		wordWrap,
		preserveIndent = !!wordWrap,
		code,
		language,
		tabSize = 2,
		lineNumbers,
		lineNumberStart,
		className,
	} = props
	const hasGuides = !!guideIndents && !rtl
	const lnOffset = lineNumberStart! - 1 || 0

	const normalizedCode = useMemo(() => {
		return preserveIndent ? code.replace(/\t/g, " ".repeat(tabSize)) : code
	}, [code, preserveIndent && tabSize])

	const lines = useMemo(() => {
		let tokens = tokenizeText(
			normalizedCode.includes("\r") ? normalizedCode.replace(/\r\n?/g, "\n") : normalizedCode,
			languages[language] || {},
		)
		onTokenize?.(tokens)
		return highlightTokens(tokens).split("\n")
	}, [onTokenize, language, normalizedCode])

	const indents = useMemo(() => {
		if (preserveIndent || hasGuides) {
			const lines = code.split("\n")
			const l = lines.length
			const result = Array<number>(l).fill(0)

			for (let prevIndent = 0, emptyPos = -1, i = 0; i < l; i++) {
				let line = lines[i]
				let l = line.search(/\S/)
				let indent = 0
				if (l < 0) {
					if (emptyPos < 0) emptyPos = i
				} else {
					for (let i = 0; i < l; ) {
						indent += line[i++] == "\t" ? tabSize - (indent % tabSize) : 1
					}
					if (emptyPos + 1) {
						if (indent != prevIndent) prevIndent = Math.min(indent, prevIndent) + 1
						while (emptyPos < i) {
							result[emptyPos++] = prevIndent
						}
					}
					result[i] = prevIndent = indent
					emptyPos = -1
				}
			}
			return result
		}
	}, [preserveIndent || hasGuides, code, tabSize])

	const codeLines = useMemo(() => {
		const keymap: Record<string, number> = {}
		const getKey = (html: string) => {
			return html + "\n" + (keymap[html] = (keymap[html] || 0) + 1)
		}

		return lines.map((html, i) => (
			<div
				className="pce-line"
				key={getKey(html)}
				style={{
					["--indent" as any]: `${indents?.[i] || 0}ch`,
				}}
				dangerouslySetInnerHTML={{ __html: html + "\n" }}
			/>
		))
	}, [lines, indents])

	const codeBlock = useStableRef<PrismCodeBlock>({})

	return (
		<pre
			className={`prism-code-editor language-${language}${
				lineNumbers ? " show-line-numbers" : ""
			} pce-${wordWrap ? "" : "no"}wrap${rtl ? " pce-rtl" : ""}${
				preserveIndent ? " pce-preserve" : ""
			}${hasGuides ? " pce-guides" : ""}${className ? " " + className : ""}`}
			ref={useStableRef((el: HTMLPreElement | null) => {
				if (el) {
					codeBlock.container = el
					codeBlock.lines = (codeBlock.wrapper = el.firstChild as HTMLElement)
						.children as HTMLCollectionOf<HTMLDivElement>
				}
			})}
			style={{
				...props.style,
				["--tab-size" as any]: tabSize,
				["--number-width" as any]: (0 | Math.log10(lines.length + lnOffset)) + 1 + ".001ch",
				counterReset: `line ${lnOffset}`,
			}}
		>
			<code className="pce-wrapper">
				<div className="pce-overlays">{props.children?.(codeBlock, props)}</div>
				{codeLines}
			</code>
		</pre>
	)
}

export * from "./brackets"
export * from "./copy"
export * from "./hover"
export { CodeBlock }

// solid-package/src/code-block/index.ts
import { Accessor, createComponent, createMemo, createRenderEffect, For, JSX } from "solid-js"
import { highlightTokens, languages, tokenizeText, TokenStream } from "../prism/index"
import { insert, style, template } from "solid-js/web"

export type CodeBlockProps = {
	/** Language used for syntax highlighting. */
	language: string
	/** Code in the code block. */
	code: string
	/** Number of spaces a tab is equal to. @default 2 */
	tabSize?: number
	/** Whether or not to display line numbers. @default false */
	lineNumbers?: boolean
	/** Line number of the first line. @default 1 */
	lineNumberStart?: number
	/** Whether or not lines can wrap. @default false */
	wordWrap?: boolean
	/**
	 * Whether or not indentation is preserved on wrapped lines. When `true`, tabs are
	 * replaced with spaces since Chrome doesn't render tabs properly with this enabled.
	 * Defaults to `true` when `wordWrap` is enabled.
	 */
	preserveIndent?: boolean
	/**
	 * Whether or not to display indentation guides. Does support `wordWrap` unlike the
	 * `indentGuides()` editor extension. Does not work with `rtl`. @default false
	 */
	guideIndents?: boolean
	/**
	 * Whether the code block uses right to left directionality. Requires styles from
	 * `solid-prism-editor/rtl-layout.css` to work. @default false
	 */
	rtl?: boolean
	/** Inline styles for the container element. */
	style?: Omit<JSX.CSSProperties, "tab-size" | "counter-reset">
	/** Additional classes for the container element. */
	class?: string
	/**
	 * Callback that can be used to modify the tokens before they're stringified to HTML.
	 * Can be used to add rainbow brackets for example.
	 */
	onTokenize?(tokens: TokenStream): void
	overlays?: CodeBlockOverlay[]
}

export type PrismCodeBlock = {
	/** Outermost element of the code block. */
	readonly container: HTMLPreElement
	/** `<code>` element wrapping the lines and overlays. */
	readonly wrapper: HTMLElement
	/**
	 * Collection containing the overlays as the first element. The rest of the elements
	 * are the code lines. This means the first line starts at index 1.
	 */
	readonly lines: HTMLCollectionOf<HTMLDivElement>
}

export type CodeBlockOverlay = (
	codeBlock: PrismCodeBlock,
	props: CodeBlockProps,
) => JSX.Element | void

const block = template("<pre><code class=pce-wrapper><div class=pce-overlays>")
const line = template("<div class=pce-line>")

const CodeBlock = (props: CodeBlockProps) => {
	const hasGuides = createMemo(() => props.guideIndents && !props.rtl)
	const preserve = createMemo(() => props.preserveIndent ?? props.wordWrap)
	const lines = createMemo(() => {
		let code = preserve() ? props.code.replace(/\t/g, " ".repeat(props.tabSize || 2)) : props.code
		let tokens = tokenizeText(
			code.includes("\r") ? code.replace(/\r\n?/g, "\n") : code,
			languages[props.language] || {},
		)
		props.onTokenize?.(tokens)
		return highlightTokens(tokens).split("\n")
	})
	const container = block() as HTMLPreElement
	const wrapper = container.firstChild as HTMLElement
	const lineEls = wrapper.children as HTMLCollectionOf<HTMLDivElement>

	const indents = createMemo(() => {
		if (preserve() || hasGuides()) {
			const code = props.code
			const tabSize = props.tabSize || 2
			const lines = code.split("\n")
			const l = lines.length
			const result: number[] = Array(l).fill(0)

			for (let prevIndent = 0, emptyPos = -1, i = 0; i < l; i++) {
				let line = lines[i]
				let l = line.search(/\S/)
				let indent = 0
				if (l < 0) {
					if (emptyPos < 0) emptyPos = i
				} else {
					for (let i = 0; i < l; ) {
						indent += line[i++] == "\t" ? tabSize - (indent % tabSize) : 1
					}
					if (emptyPos + 1) {
						if (indent != prevIndent) prevIndent = Math.min(indent, prevIndent) + 1
						while (emptyPos < i) {
							result[emptyPos++] = prevIndent
						}
					}
					result[i] = prevIndent = indent
					emptyPos = -1
				}
			}
			return result
		}
	})

	const codeBlock = {
		container,
		wrapper,
		lines: lineEls,
	}

	insert(
		lineEls[0],
		createComponent(For, {
			get each() {
				return props.overlays
			},
			children: (overlay: CodeBlockOverlay) => overlay(codeBlock, props)!,
		}),
		null,
	)

	insert(
		wrapper,
		createComponent(For, {
			get each() {
				return lines()
			},
			children: (html: string, i: Accessor<number>) => {
				const div = line() as HTMLDivElement
				div.innerHTML = html + "\n"
				createRenderEffect(() => {
					div.style.setProperty("--indent", `${indents()?.[i()] || 0}ch`)
				})
				return div
			},
		}),
		null,
	)

	createRenderEffect(() => {
		let propClass = props.class
		container.className = `prism-code-editor language-${props.language}${
			props.lineNumbers ? " show-line-numbers" : ""
		} pce-${props.wordWrap ? "" : "no"}wrap${props.rtl ? " pce-rtl" : ""}${
			preserve() ? " pce-preserve" : ""
		}${hasGuides() ? " pce-guides" : ""}${propClass ? " " + propClass : ""}`
	})

	createRenderEffect<Record<string, string>>(
		prev => style(container, props.style as Record<string, string>, prev)!,
	)

	createRenderEffect(() => {
		const style = container.style
		const offset = props.lineNumberStart! - 1 || 0
		style.setProperty("--tab-size", props.tabSize || (2 as any))
		style.setProperty("--number-width", (0 | Math.log10(lines().length + offset)) + 1 + ".001ch")
		style.counterReset = `line ${offset}`
	})

	return container
}

export * from "./brackets"
export * from "./copy"
export * from "./hover"
export { CodeBlock }
